$s=function(a){a.STATUS_ERROR=1;"send_timeout"in a||(a.send_timeout=500);"url"in a&&(a.enabled=!0);a.request_count=0;a._requests=[];a.Request=function(b,d){this.request_id=a.request_count++;a._requests[this.request_id]=this;this.time_start=+new Date;this.time_end=0;this.host_name="";this.script_name=b||a.page||location.pathname;this.tags=d;this.status=this.value=0;this.timers=[];this.timers_active=0;this._tmap={};this._sended=this._aborted=this._ended=!1};a.Request.prototype={set_start:function(b){this.time_start=
b},set_host_name:function(b){this.host_name=b},set_script_name:function(b){this.script_name=b||a.page||location.pathname},abort:function(){this.timers_stop();this._aborted=!0},end:function(b){if(!this._aborted&&!this._sended){this._ended=!0;b&&(this.status=b);if(this.timers_active)return!1;this.time_end=+new Date;this.value=this.time_end-this.time_start;this.send();return!0}},send:function(){!this._aborted&&!this._sended&&(a.send_pool.push(this),this._sended=!0)},timer_add:function(b,d){var c=new a.Timer(b,
d);this.timers.push(c)},timer_start:function(b,d){var c=new a.Timer(d);this.timers.push(c);this._tmap[b]=c;this.timers_active++},timer_stop:function(b){b=this._tmap[b];if(!b)return!1;b.stop();this.timers_active--;this._ended&&0==this.timers_active&&this.end();return!0},timer_tags_merge:function(b,a){var c=this._tmap[b];if(!c)return!1;if(c.tags)for(var g in a)c.tags[g]=a[g];else c.tags=a;return!0},timers_stop:function(){for(var b=0,a=this.timers.length;b<a;b++)this.timers[b].stop();this.timers_active=
0;this._ended&&this.end()},toJSON:function(){for(var b=[],a=0,c=this.timers.length;a<c;a++)b.push(this.timers[a].toJSON());return{host_name:this.host_name,script_name:this.script_name,value:this.value,timers:b,tags:this.tags}},getTimes:function(){for(var b={},a=0,c=this.timers.length;a<c;a++)b[this.timers[a].tags.group]=this.timers[a].value;return b}};a.Timer=function(b,a){this.time_start=a?0:+new Date;this.time_end=0;this.tags=b;this.value=a||0};a.Timer.prototype={stop:function(){!this.time_end&&
this.time_start&&(this.time_end=+new Date,this.value=this.time_end-this.time_start)},toJSON:function(){return{tags:this.tags,value:this.value}}};a.SendPool=function(){this._pool=[];this._timer=0};a.SendPool.prototype={push:function(b){!1===a.enabled?delete a._requests[b.request_id]:(this._pool.push(b),this.start_timer())},start_timer:function(){if(!this._timer&&this._pool.length&&a.enabled){var b=this;this._timer=setTimeout(function(){b.send()},a.send_timeout)}},get_data:function(){for(var b=[],d=
0,c=this._pool.length;d<c;d++)b[d]=this._pool[d].toJSON(),delete a._requests[this._pool[d].request_id];this._pool=[];return b},clear_data:function(){for(var b=0,d=this._pool.length;b<d;b++)delete a._requests[this._pool[b].request_id];this._pool=[]},send:function(){this._timer=0;var b=this.get_data();if(a.url&&window.JSON&&window.XMLHttpRequest){var d=new XMLHttpRequest;d.open("POST",a.url,!0);d.setRequestHeader("Content-Type","text/plain");d.send(JSON.stringify(b))}}};a.send_pool=new a.SendPool;a.r=
function(b){return a._requests[b]};a.enable=function(b){b?(a.url=b,a.enabled=!0,a.send_pool.start_timer()):(a.enabled=!1,a.send_pool.clear_data())};return a}(window.$s||{});
(function(a){if(a){var b=window,d=b.performance||b.msPerformance||b.webkitPerformance||b.mozPerformance,c=d&&d.timing;a.timing_supported=!!c;a.add_timing=c?function(a){function d(){a.timer_add({group:"response"},c.responseEnd-c.responseStart);a.timer_add({group:"dom_loading"},c.domInteractive-c.responseEnd);a.timer_add({group:"dom_interactive"},c.domContentLoadedEventStart-c.domInteractive);a.timer_add({group:"dom_loaded"},c.domContentLoadedEventEnd-c.domContentLoadedEventStart);a.timer_add({group:"ttfb"},
c.responseStart-e);a.timer_add({group:"dom_ready"},c.domContentLoadedEventStart-e);a.timer_add({group:"usable"},c.domContentLoadedEventEnd-e)}function f(){a.timer_add({group:"photo_load"},c.loadEventEnd-c.domContentLoadedEventEnd);a.timer_add({group:"on_load"},c.loadEventEnd-e)}function h(){setTimeout(f,100);a.end()}var e=c.navigationStart||c.fetchStart;e?(a.set_start(e),a.timer_add({group:"dns"},c.domainLookupEnd-c.domainLookupStart),a.timer_add({group:"connect"},c.connectEnd-c.connectStart),a.timer_add({group:"wait"},
c.responseStart-c.connectEnd),setTimeout(d,100),b.addEventListener?b.addEventListener("load",h,!1):b.attachEvent("onload",h)):(a.timer_add({group:"navtime_error"},0),b.addEventListener?b.addEventListener("load",a.end.bind(a),!1):b.attachEvent("onload",a.end.bind(a)))}:function(c){function d(){c.timer_add({group:"on_load"},+new Date-a.fake_start);c.end()}c.set_start(a.fake_start);c.timer_add({group:"dom_ready"},+new Date-a.fake_start);b.addEventListener?b.addEventListener("load",d,!1):b.attachEvent("onload",
d)}}})(window.$s);window._badoo_webapp_version="2.1.2";window._badoo_webapp_build=1389187632042;window._badoo_webapp_desc="prod";var Badoo=Badoo||{};
(function(a){var b=window.$s;b.send_timeout=2E3;b.url=null;var d;a:{var c=navigator.userAgent,g=navigator.platform,i="",f="",h="",g=(g||"").toLowerCase();if("android"===g||/android/i.test(c))i="android",f=null!==(f=c.match(/Android (\d+(?:\.\d+)+);/))?f[1]:"",h=/firefox/i.test(c)?"firefox":/chrome/i.test(c)?"chrome":"other";else if("iphone"===g||"ipad"===g||/iphone|ipad/gi.test(c))i=c.match(/iphone|ipad/gi)[0],f=null!==(f=c.match(/iPhone OS (\d+)_(\d+)\s+/i))?f[1]:"",h=/CriOS/.test(c)?"chrome":"safari";
else{d="other";break a}d=i+(f?"-"+f:"")+(h?"-"+h:"")}var e=function(){};e.prototype={enabled_:!0,jinbaInitialised_:!1,startupRequest_:null,currentAction_:null,EVENT_REGEX:/^([\w\-]+?)\-(start|end)$/,getStartupRequest:function(){this.startupRequest_||(this.startupRequest_=e.getRequest("startup"),this.startupRequest_.set_start(b.fake_start));return this.startupRequest_},startupEvent:function(a,b){if(!this.enabled_)return this;var c=this.parseEvent_(a);if(null===c)return this;var d=this.getStartupRequest();
c.isStart?d.timer_start(c.name,this.extend_({group:c.name},b)):(b&&d.timer_tags_merge(c.name,b),d.timer_stop(c.name));return this},actionStart:function(a){if(!a||!this.enabled_)return this;"string"===typeof a&&(a={name:a});if(this.currentAction_&&this.currentAction_.name===a.name)return this;this.currentAction_={name:a.name,timers:{},startTime:a.startTime||(new Date).getTime()};return this},actionEnd:function(a){if(!this.enabled_||!this.currentAction_||this.currentAction_.name!==a)return this;a=this.currentAction_;
a.duration=(new Date).getTime()-a.startTime;var b=e.getRequest(a.name);b.set_start(a.startTime);for(var c in a.timers)a.timers.hasOwnProperty(c)&&a.timers[c].ended&&b.timer_add(a.timers[c].tags,a.timers[c].duration);b.end();this.currentAction_=null;return this},event:function(a,b){if(!this.currentAction_||!this.enabled_)return this;var c=this.parseEvent_(a);if(null===c)return this;var d=this.currentAction_.timers;if(c.isStart)return d[c.name]={name:c.name,startTime:(new Date).getTime(),ended:!1,tags:this.extend_({group:c.name},
b)},this;if(c=d[c.name])c.ended=!0,c.duration=(new Date).getTime()-c.startTime,this.extend_(c.tags,b);return this},setUrl:function(a){if(this.jinbaInitialised_)return this;this.jinbaInitialised_=!0;if(!a)return this.enabled_=!1,this.startupRequest_=null,b.enable(!1),this;b.enable(a);return this},parseEvent_:function(a){a=this.EVENT_REGEX.exec((a||"").toLowerCase());return null===a||3!==a.length?null:{name:a[1],isStart:"start"===a[2]}},extend_:function(a,b){var a=a||{},b=b||{},c;for(c in b)b.hasOwnProperty(c)&&
(a[c]=b[c]);return a}};var j;e.getInstance=function(){return j||(j=new e)};e.getRequest=function(a,c){var f=new b.Request(a,e.prototype.extend_({mode:!0===b.is_native?"hon-native":"hon",app_version:window._badoo_webapp_build,ua:d},c));f.set_host_name(window.location.hostname);return f};a.Utils=a.Utils||{};a.Utils.Timing=e;e.getInstance().startupEvent("load-js-start");document.addEventListener("DOMContentLoaded",function(){b.add_timing(e.getInstance().getStartupRequest())},!1)})(Badoo);